### ISSUE TITLE
Is the cookbook for this still under development?

### ISSUE THREAD

**Issue by paulius005** [zuazo/chef-handler-sns#11]
Posting here as well since I noticed a lack of activity for the past year on the cookbook.

Is it still under development? If not, what would need to be done to bring it up to date with this repo.

Looks like the cookbook IS pulling in the latest gem in the issue.

Not sure if my issue is related but the mentioned issue is here: https://github.com/zuazo/chef_handler_sns-cookbook/issues/5

**Comment by zuazo** [comment]
I'm not using that cookbook nowadays and it requires some updates. But I try to do the maintenance on my own. Feel free to send a PR with fixes, or open any issue you find, just like you have already done.
