### ISSUE TITLE
message_structure support

### ISSUE THREAD

**Issue by d-averkiev** [zuazo/chef-handler-sns#9]
Hello. I'm trying to use the chef-handler-sns cookbook to send SNS notification to few different endpoints (email, lambda). But [report function](https://github.com/zuazo/chef-handler-sns/blob/master/lib/chef/handler/sns.rb#L133) sends messages without defining [message_structure](http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html#publish-instance_method) option. Can you add support for message_structure?
Btw, if message_structure defined for client.publish() method but has empty (not 'json') value message will be send as plain text.

**Comment by zuazo** [comment]
Closing in favor of #10.
